dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - doxygen

install:
- DEPS="${TRAVIS_BUILD_DIR}/deps"
- mkdir -p ${DEPS}
- |
  if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew update
    brew upgrade cmake
  elif [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    travis_retry wget --no-check-certificate https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.sh
    bash cmake-3.8.2-Linux-x86_64.sh --skip-license --prefix="${DEPS}"
    export PATH="${DEPS}/bin:${PATH}"
  fi

script:
- export CC=/usr/bin/gcc-5 CXX=/usr/bin/g++-5
- git submodule update --init --recursive
- mkdir build-debug
- cd build-debug
- cmake .. -DCMAKE_BUILD_TYPE=Debug -DTAG_FMT_INCLUDE_UNIT_TESTS=ON
- cmake --build . -- -j2
- cd ..
- mkdir build-release
- cd build-release
- cmake .. -DCMAKE_BUILD_TYPE=Release -DTAG_FMT_INCLUDE_UNIT_TESTS=ON
- cmake --build . --target install -- -j2
- cd ..

after_success:
- doxygen Doxyfile

# run unit test and code coverage
- ./build-debug/tag_fmt_unit_test -s
- ./build-release/tag_fmt_unit_test -s
# - gcov ./build-debug/CMakeFiles/tag_fmt_unit_test.dir/src/unit_test/unit_test.cpp.gcno
# - bash <(curl -s https://codecov.io/bash)