environment:
  global:
    PROJECT_NAME: tag_fmt

  matrix:
     - GENERATOR: "Visual Studio 14"
       CONFIG: Debug
     - GENERATOR: "Visual Studio 14"
       CONFIG: Release

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 Win64"
  - msbuild /m:4 /p:Config=Debug tag_fmt.sln
  - msbuild /m:4 /p:Config=Release tag_fmt.sln
